# Generated by Django 2.2.2 on 2019-06-19 20:12
from django.db import migrations
from django.contrib.auth.models import Group

from users.enums import GroupType


def generate_groups(apps, schema_editor):
    Group.objects.create(name=GroupType.customer.value)
    Group.objects.create(name=GroupType.washer.value)
    Group.objects.create(name=GroupType.worker.value)


def delete_groups(apps, schema_editor):
    Group.objects.filter(name=GroupType.customer.value).delete()
    Group.objects.filter(name=GroupType.washer.value).delete()
    Group.objects.filter(name=GroupType.worker.value).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_groups, delete_groups)
    ]
