# Generated by Django 2.2.2 on 2019-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_smsmessage_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
