# Generated by Django 2.2.2 on 2019-06-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='washer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.WasherProfile'),
        ),
    ]
