# Generated by Django 2.2.2 on 2019-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_smsmessagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessagemodel',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
