# Generated by Django 2.2.2 on 2019-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workerprofile_washer_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='washerprofile',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='workerprofile',
            options={'ordering': ['-created_date']},
        ),
    ]
