# Generated by Django 2.2.2 on 2019-09-14 13:54

from django.db import migrations
import enumfields.fields
import users.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190804_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=enumfields.fields.EnumField(enum=users.enums.Gender, max_length=10, null=True),
        ),
    ]
