# Generated by Django 2.2.2 on 2020-01-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190801_1628'),
        ('users', '0005_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='stores.Store')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_profile', to='users.WorkerProfile')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
