# Generated by Django 2.2.2 on 2019-07-17 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190717_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
