# Generated by Django 2.2.2 on 2020-02-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_workerjoblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsMessage',
        ),
    ]
