# Generated by Django 2.2.2 on 2019-07-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190717_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmsMessageModel',
            new_name='SmsMessage',
        ),
    ]
