image: "python:3.7"

services:
  - postgres:latest
  - redis:latest
  - name: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    alias: elasticsearch-unit
    command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]

variables:
  ELASTICSEARCH_HOST: elasticsearch-unit
  ELASTICSEARCH_PORT: 9200
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: "test"


before_script:
  - curl "http://elasticsearch-unit:9200/_cat/health"
  - apt-get install libjpeg62-turbo-dev
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python manage.py test --settings=washer_project.settings_gitlab_ci
  only:
    - tags
    - merge_requests