image: "python:3.7"

before_script:
  - apt-get install libjpeg8-dev postgresql elasticsearch
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test --settings=washer_project.settings
