image: python:3.7.3

pipelines:
  branches:
    '*':
      - step:
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - sh scripts/run_pytests_bitbucket_pipeline.sh
          services:
            - database
            - caching
            - elastic
definitions:
  services:
    database:
      image: postgres:10-alpine
    caching:
      image: redis:4.0.14-alpine
    elastic:
      image: elasticsearch:7.2.0-alpine
