# Generated by Django 2.2.2 on 2019-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import reservations.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0002_auto_20190801_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', enumfields.fields.EnumField(db_index=True, default='100', enum=reservations.enums.ReservationStatus, max_length=10)),
                ('period', models.PositiveSmallIntegerField()),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('basket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baskets.Basket')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
