# Generated by Django 2.2.2 on 2019-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0003_customerprofile_smsmessage_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.Store'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reservations.Reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('start_datetime', 'store')},
        ),
    ]
