# Generated by Django 2.2.2 on 2019-07-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20190721_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
    ]
