# Generated by Django 2.2.2 on 2019-07-30 18:16

import baskets.enums
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField()),
                ('promotion_type', enumfields.fields.EnumField(enum=baskets.enums.PromotionType, max_length=32)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='DiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baskets.Basket')),
                ('basket_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_item', to='baskets.BasketItem')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baskets.Campaign')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
