# Generated by Django 2.2.2 on 2019-06-23 15:22

import cars.enums
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customerprofile_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('licence_plate', models.CharField(max_length=9)),
                ('car_type', enumfields.fields.EnumField(enum=cars.enums.CarType, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.CustomerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
