# Generated by Django 2.2.2 on 2019-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
