# Generated by Django 2.2.2 on 2019-07-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0003_customerprofile_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.CustomerProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('licence_plate', 'customer_profile')},
        ),
    ]
