# Generated by Django 2.2.2 on 2019-07-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190705_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set(),
        ),
    ]
