from django.utils.translation import ugettext_lazy as _

from enumfields import Enum


class ReservationStatus(Enum):
    available = '100'  # generated by system
    occupied = '200'   # occupied by customer
    reserved = '300'   # reserved by customer
    started = '350'    # process started by washer or worker
    completed = '400'  # process completed by washer or worker
    cancelled = '500'  # cancel !reserved! reservation by washer or worker or customer
    disabled = '550'   # disable by washer or worker
    expired = '600'    # expire by system
    # closed = '650'   # close by system

    class Labels:
        available = _('Available')
        occupied = _('Occupied')
        reserved = _('Reserved')
        started = _('Started')
        completed = _('Completed')
        cancelled = _('Cancelled')
        disabled = _('Disabled')
        expired = _('Expired')

    def __gt__(self, other):
        return int(self.value) > int(other.value)

    def __ge__(self, other):
        return int(self.value) >= int(other.value)

    def __lt__(self, other):
        return int(self.value) < int(other.value)

    def __le__(self, other):
        return int(self.value) <= int(other.value)
