from django.utils.translation import ugettext_lazy as _

from enumfields import Enum


class ReservationStatus(Enum):
    available = '100'  # generated by system
    occupied = '200'  # occupied by customer
    reserved = '300'  # reserved by customer
    started = '350'  # process started by washer or worker
    completed = '400'  # process completed by washer or worker
    cancelled = '500'  # cancel reserved reservation by washer or worker
    expired = '530'  # expire by system
    disabled = '560'  # disable by washer or worker

    class Labels:
        available = _('Available')
        occupied = _('Occupied')
        reserved = _('Reserved')
        started = _('Started')
        completed = _('Completed')
        cancelled = _('Cancelled')
        expired = _('Expired')
        disabled = _('Disabled')

    def __gt__(self, other):
        return int(self.value) > int(other.value)

    def __ge__(self, other):
        return int(self.value) >= int(other.value)

    def __lt__(self, other):
        return int(self.value) < int(other.value)

    def __le__(self, other):
        return int(self.value) <= int(other.value)
