# Generated by Django 2.2.2 on 2019-06-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='tr', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
