# Generated by Django 2.2.2 on 2019-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20190628_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_date']},
        ),
    ]
