# Generated by Django 2.2.2 on 2019-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0003_customerprofile_smsmessage_washerprofile_workerprofile'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimageitem',
            name='washer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WasherProfile'),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
        migrations.AddField(
            model_name='store',
            name='washer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.WasherProfile'),
        ),
    ]
