# Generated by Django 2.2.2 on 2019-06-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0003_customerprofile_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='washer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.WasherProfile'),
        ),
    ]
