# Generated by Django 2.2.2 on 2019-06-30 17:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190625_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'opening_hours': dict, 'reservation_hours': dict}),
        ),
        migrations.AlterField(
            model_name='store',
            name='washer_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.WasherProfile'),
            preserve_default=False,
        ),
    ]
