# Generated by Django 2.2.2 on 2019-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190716_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
