# Generated by Django 2.2.2 on 2019-07-22 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190716_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payment_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
