# Generated by Django 2.2.2 on 2019-06-30 18:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190630_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
