# Generated by Django 2.2.2 on 2019-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20190630_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_date']},
        ),
    ]
