# Generated by Django 2.2.2 on 2019-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
