# Generated by Django 2.2.2 on 2019-07-27 13:20

from django.db import migrations
import enumfields.fields
import notifications.enums


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=enumfields.fields.EnumField(enum=notifications.enums.NotificationType, max_length=32),
        ),
    ]
