# Generated by Django 2.2.2 on 2019-07-06 17:08

import cars.enums
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import products.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store_washer_profile'),
        ('users', '0003_customerprofile_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('product_type', enumfields.fields.EnumField(enum=products.enums.ProductType, max_length=10)),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('period', models.PositiveSmallIntegerField(default=None, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
                ('washer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WasherProfile')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', enumfields.fields.EnumField(default='try', enum=products.enums.Currency, max_length=10)),
                ('car_type', enumfields.fields.EnumField(enum=cars.enums.CarType, max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'unique_together': {('product', 'car_type')},
            },
        ),
    ]
