# Generated by Django 2.2.2 on 2019-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
